### ISSUE TITLE
spellcrafting combine not working

### ISSUE THREAD

**Issue by PeterV1982** [Dawn-of-Light/DOLSharp#255]
![sshot005](https://user-images.githubusercontent.com/16477238/93878822-fadbcb80-fcda-11ea-97fd-1e9c8953575e.jpg)
but the not powerfull enough is before i even add a gem.

i know for sure it used to work
added a screenshot, hope it helps in finding the issue

**Comment by tegstewart** [comment]
After some more fiddling, I've found a few interesting things.

First, it always says you don't have enough skill to imbue an item when you first open the combine window, before you add any gems.  No idea how that's happening, since the only time that error message appears in code isn't being reached until you add a gem, but it doesn't stop you from being able to do the combine.  Can you confirm that you can't accept the imbue, and that this isn't just an incorrect error message?

Second, it's supposed to show you how many imbue points you've used as you add each gem.  I think I've found an issue with the packet handling for trade windows that would cause something similar, but it stopped me from adding gems at all, which clearly isn't the case here.

**Comment by NetDwarf** [comment]
This issue can be closed. The error was on Storm and was triggered by one of the items not being tradable.
