### ISSUE TITLE
Question - What's the point of this block of code (what appears to send player positions that are out of range without isVisible check)

### ISSUE THREAD

**Issue by ahungry** [Dawn-of-Light/DOLSharp#260]
https://github.com/Dawn-of-Light/DOLSharp/blob/master/GameServer/world/WorldUpdateThread.cs#L185

It looks like the preceding section of code sends out player locations/updates for players within range (3600 units or less by default).

Then, this section looks like it sends out the rest of the player locations (in zone?).

If the server only sent out positions of players in range, what would be the consequence?  Would it reduce radar viability?  Would it have bad side-effects on the client side?

**Comment by ahungry** [comment]
I may have read it too hastily - I think "players" is already scoped to those in range, but the second section doesn't seem to perform the same isVisible check (LOS?) the first one does.

**Comment by dol-leodagan** [comment]
@ahungry 

The first section is the Player Cache Cleanup, it handles every player being in cache for the current "viewer" but not being in the "players" collection that contains only "In Range", "Visible To", not "Stealth" and not "Detected".

The Cache Cleanup removes the other agents from the "viewer" cache to be able to send updates right when they get back into visibility.

The code block beginning at L185 is the real update loop that actually only send player update for those not being in cache and those in cache but obsolete.

The agents in cache cleanup are tested for Stealth and Detection because they're not in the initial filtered "players" collection, and removing a player from cache sends a last update to make sure they're updated "out of view" (preventing the previous update from sending a vector that will cross the "viewer" path, but that's not ideal...)

**Comment by ahungry** [comment]
Thanks!
